Config = {}
Config.Job = "tuner"
--Shop
Config = {
    MechanicItems = {
    [1] = {
        name = 'repairkit',
        price = 1000,
        amount = 75,
        info = {},
        type = 'item',
        slot = 1,
       
    },
    [2] = {
        name = "advancedrepairkit",
        price = 1750,
        amount = 50,
        info = {},
        type = "item",
        slot = 2,
       
    },
    [3] = {
        name = "nitrous",
        price = 4000,
        amount = 25,
        info = {},
        type = "item",
        slot = 3,
        
    },
    [4] = {
        name = "harness",
        price = 2500,
        amount = 35,
        info = {},
        type = "item",
        slot = 4,
        
    },
    [5] = {
        name = "cleaningkit",
        price = 750,
        amount = 25,
        info = {},
        type = "item",
        slot = 5,           
    },
    [6] = {
        name = "pixellaptop",
        price = 25000,
        amount = 10,
        info = {},
        type = "item",
        slot = 6,           
    },
    [7] = {
        name = "disabler",
        price = 2000,
        amount = 10,
        info = {},
        type = "item",
        slot = 7,        
    },
    [8] = {
        name = "turbo",
        price = 2000,
        amount = 10,
        info = {},
        type = "item",
        slot = 7,           
    },
    [9] = {
        name = "translv1",
        price = 2000,
        amount = 10,
        info = {},
        type = "item",
        slot = 8,           
    },
    [10] = {
        name = "translv2",
        price = 2000,
        amount = 10,
        info = {},
        type = "item",
        slot = 9,           
    },
    [11] = {
        name = "translv3",
        price = 2000,
        amount = 10,
        info = {},
        type = "item",
        slot = 10,           
    },
    [12] = {
        name = "englv1",
        price = 2000,
        amount = 10,
        info = {},
        type = "item",
        slot = 11,           
    },
    [13] = {
        name = "englv2",
        price = 2000,
        amount = 10,
        info = {},
        type = "item",
        slot = 12,           
    },
    [14] = {
        name = "englv3",
        price = 2000,
        amount = 10,
        info = {},
        type = "item",
        slot = 13,           
    },
    [15] = {
        name = "englv4",
        price = 2000,
        amount = 10,
        info = {},
        type = "item",
        slot = 14,           
    },
    [16] = {
        name = "brakeslv1",
        price = 2000,
        amount = 10,
        info = {},
        type = "item",
        slot = 15,           
    },
    [17] = {
        name = "brakeslv2",
        price = 2000,
        amount = 10,
        info = {},
        type = "item",
        slot = 16,           
    },
    [18] = {
        name = "brakeslv3",
        price = 2000,
        amount = 10,
        info = {},
        type = "item",
        slot = 17,              
    },
    [19] = {
        name = "suslv1",
        price = 2000,
        amount = 10,
        info = {},
        type = "item",
        slot = 18,              
    },
    [20] = {
        name = "suslv2",
        price = 2000,
        amount = 10,
        info = {},
        type = "item",
        slot = 19,              
    },
    [21] = {
        name = "suslv3",
        price = 2000,
        amount = 10,
        info = {},
        type = "item",
        slot = 20,              
    },
    [22] = {
        name = "suslv4",
        price = 2000,
        amount = 10,
        info = {},
        type = "item",
        slot = 20,              
    },
    },
    }
    